import test from 'node:test';
import assert from 'node:assert/strict';
import { parseMusicUrl, isShortMusicLink, normalize, sameTrackTitle, selectUniqueTitleArtist, cleanTrackUrl } from './lib.js';
import { extractJsonAfter } from './http.js';
import { parseAutoGeneratedDescription, youtubeSongFromPlayer, parseMusicSearch, parseVideoSearch, cleanVideoTitle } from './youtube.js';
import { parseHydration, findClientId } from './soundcloud.js';
import { parseEmbed } from './spotify.js';
import { odesliLinks } from './odesli.js';

const artistRun = text => ({ text, navigationEndpoint: { browseEndpoint: { browseEndpointContextSupportedConfigs: { browseEndpointContextMusicConfig: { pageType: 'MUSIC_PAGE_TYPE_ARTIST' } } } } });
const musicSearchItem = (videoId, title, runs) => ({ musicResponsiveListItemRenderer: {
  playlistItemData: { videoId },
  flexColumns: [
    { musicResponsiveListItemFlexColumnRenderer: { text: { runs: [{ text: title }] } } },
    { musicResponsiveListItemFlexColumnRenderer: { text: { runs } } }
  ]
} });

test('accepts YouTube, youtu.be and mobile SoundCloud track links', () => {
  assert.equal(parseMusicUrl('https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=x').url, 'https://music.youtube.com/watch?v=dQw4w9WgXcQ');
  assert.equal(parseMusicUrl('https://youtu.be/dQw4w9WgXcQ?si=abc').url, 'https://music.youtube.com/watch?v=dQw4w9WgXcQ');
  assert.equal(parseMusicUrl('https://m.soundcloud.com/artist/song?si=1').url, 'https://soundcloud.com/artist/song');
  assert.throws(() => parseMusicUrl('https://soundcloud.com/artist/sets/album'));
  assert.throws(() => parseMusicUrl('https://soundcloud.com/discover/sets'));
  assert.equal(isShortMusicLink('https://on.soundcloud.com/AbCd'), true);
  assert.equal(isShortMusicLink('https://example.com/AbCd'), false);
});

test('compares Spotify "- Remastered" titles with Apple parenthesised titles', () => {
  assert.equal(normalize('Yesterday - Remastered 2009'), 'yesterday');
  assert.equal(sameTrackTitle('Yesterday - Remastered 2009', 'Yesterday (Remastered 2009)'), true);
  assert.equal(sameTrackTitle('Yesterday - Remastered 2009', 'Yesterday'), false);
  assert.equal(normalize('Sen - Ben'), 'sen ben');
});

test('reads title, artists and album from an auto-generated YouTube description', () => {
  const description = 'Provided to YouTube by DMC\n\nDivane · Yaşar\n\nDivane\n\n℗ 2019 DMC\n\nReleased on: 2019-05-10\n\nAuto-generated by YouTube.';
  assert.deepEqual(parseAutoGeneratedDescription(description), { title: 'Divane', artist: 'Yaşar', album: 'Divane' });
  const player = { videoDetails: { title: 'Divane', author: 'Yaşar - Topic', lengthSeconds: '252', shortDescription: description } };
  assert.equal(youtubeSongFromPlayer(player).duration, 252000);
  assert.equal(youtubeSongFromPlayer(player).durationReliable, true);
});

test('splits a music video title and marks its duration as unreliable', () => {
  const song = youtubeSongFromPlayer({ videoDetails: { title: 'Tarkan - Şımarık (Official Video)', author: 'TarkanVEVO', lengthSeconds: '260', shortDescription: '' } });
  assert.equal(song.artist, 'Tarkan');
  assert.equal(normalize(song.title), 'şımarık');
  assert.equal(song.durationReliable, false);
});

test('extracts page JSON even when strings contain braces', () => {
  const html = '<script>var ytInitialPlayerResponse = {"a":"}{","b":[1,{"c":2}]};var x = 1;</script>';
  assert.deepEqual(extractJsonAfter(html, 'ytInitialPlayerResponse = '), { a: '}{', b: [1, { c: 2 }] });
});

test('parses YouTube Music song search results', () => {
  const response = { contents: { sectionListRenderer: { contents: [{ musicShelfRenderer: { contents: [
    musicSearchItem('abcdefghijk', 'Divane', [artistRun('Yaşar'), { text: ' • ' }, { text: 'Divane' }, { text: ' • ' }, { text: '4:12' }]),
    musicSearchItem('bad', 'Broken', [])
  ] } }] } } };
  assert.deepEqual(parseMusicSearch(response), [{ title: 'Divane', artist: 'Yaşar', duration: 252000, isrc: null, url: 'https://music.youtube.com/watch?v=abcdefghijk' }]);
});

test('reads SoundCloud publisher metadata including ISRC', () => {
  const data = [{ hydratable: 'user', data: {} }, { hydratable: 'sound', data: {
    title: 'Divane', full_duration: 252000, permalink_url: 'https://soundcloud.com/dmc/divane', artwork_url: 'https://i1.sndcdn.com/a-large.jpg',
    user: { username: 'DMC' }, publisher_metadata: { artist: 'Yaşar', isrc: 'trabc1900001', album_title: 'Divane' }
  } }];
  const song = parseHydration(`<script>window.__sc_hydration = ${JSON.stringify(data)};</script>`);
  assert.equal(song.artist, 'Yaşar');
  assert.equal(song.isrc, 'TRABC1900001');
  assert.equal(song.artwork, 'https://i1.sndcdn.com/a-t500x500.jpg');
  assert.equal(findClientId('x={client_id:"abcdefghijklmnopqrstuvwxyz123456"}'), 'abcdefghijklmnopqrstuvwxyz123456');
});

test('reads artists and duration from the Spotify embed page', () => {
  const next = { props: { pageProps: { state: { data: { entity: {
    type: 'track', name: 'Divane', uri: 'spotify:track:3V9Cf4pENsRh02WTMJ726n', duration: 252000,
    artists: [{ name: 'Yaşar', uri: 'spotify:artist:1' }], visualIdentity: { image: [{ url: 'small', maxWidth: 64 }, { url: 'large', maxWidth: 640 }] }
  } } } } } };
  const song = parseEmbed(`<script id="__NEXT_DATA__" type="application/json">${JSON.stringify(next)}</script>`);
  assert.deepEqual([song.title, song.artist, song.duration, song.artwork], ['Divane', 'Yaşar', 252000, 'large']);
});

test('keeps only Odesli links whose entity agrees with the source song', () => {
  const data = {
    entityUniqueId: 'YOUTUBE_VIDEO::abcdefghijk',
    entitiesByUniqueId: {
      'YOUTUBE_VIDEO::abcdefghijk': { type: 'song', title: 'Divane', artistName: 'Yaşar - Topic' },
      'SPOTIFY_SONG::1': { type: 'song', title: 'Divane', artistName: 'Yaşar' },
      'DEEZER_SONG::2': { type: 'song', title: 'Divane', artistName: 'Someone Else' },
      'ITUNES_SONG::3': { type: 'song', title: 'Divane (Live)', artistName: 'Yaşar' }
    },
    linksByPlatform: {
      youtubeMusic: { url: 'https://music.youtube.com/watch?v=abcdefghijk', entityUniqueId: 'YOUTUBE_VIDEO::abcdefghijk' },
      spotify: { url: 'https://open.spotify.com/track/3V9Cf4pENsRh02WTMJ726n?si=1', entityUniqueId: 'SPOTIFY_SONG::1' },
      deezer: { url: 'https://www.deezer.com/track/2', entityUniqueId: 'DEEZER_SONG::2' },
      appleMusic: { url: 'https://geo.music.apple.com/us/album/_/1?i=3&mt=1&app=music&at=aff', entityUniqueId: 'ITUNES_SONG::3' }
    }
  };
  const result = odesliLinks(data, { title: 'Divane', artist: '' });
  assert.equal(result.artist, 'Yaşar');
  assert.deepEqual(result.links, { spotify: 'https://open.spotify.com/track/3V9Cf4pENsRh02WTMJ726n', youtube: 'https://music.youtube.com/watch?v=abcdefghijk' });
  assert.equal(cleanTrackUrl('apple', 'https://geo.music.apple.com/us/album/_/1?i=3&mt=1&app=music&at=aff'), 'https://geo.music.apple.com/us/album/_/1?i=3');
});

test('accepts a title and artist without duration only when all such results are one recording', () => {
  const source = { title: 'Şımarık', artist: 'Tarkan', duration: 260000, durationReliable: false };
  const one = { title: 'Şımarık', artist: 'Tarkan', duration: 237000, url: 'a' };
  assert.equal(selectUniqueTitleArtist(source, [one, { ...one, duration: 238000, url: 'b' }]), one);
  assert.equal(selectUniqueTitleArtist(source, [one, { ...one, duration: 330000, url: 'c' }]), null);
  assert.equal(selectUniqueTitleArtist(source, [{ ...one, artist: 'Başkası' }]), null);
});

test('removes video labels from titles but keeps version labels', () => {
  assert.equal(cleanVideoTitle('Blinding Lights (Official Audio)'), 'Blinding Lights');
  assert.equal(cleanVideoTitle('Divane [Official Music Video]'), 'Divane');
  assert.equal(cleanVideoTitle('Şımarık (Video Klip)'), 'Şımarık');
  assert.equal(cleanVideoTitle('Get Lucky (Live)'), 'Get Lucky (Live)');
});

test('keeps only Topic and verified-artist uploads from YouTube search', () => {
  const video = (videoId, title, channel, length, badge) => ({ videoRenderer: {
    videoId, title: { runs: [{ text: title }] }, ownerText: { runs: [{ text: channel }] }, lengthText: { simpleText: length },
    ownerBadges: badge ? [{ metadataBadgeRenderer: { style: badge } }] : []
  } });
  const results = parseVideoSearch({ contents: [
    video('WiFFLGyT59I', 'Yaşar - Divane', 'Göknur Demirel', '3:53'),
    video('HhucJr-9MCk', 'Yaşar - Divane', 'Yaşar', '3:58'),
    video('OuZWcgB4INw', 'Yaşar - Divane (Official Video)', 'Yaşar', '3:41', 'BADGE_STYLE_TYPE_VERIFIED_ARTIST'),
    video('abcdefghijk', 'Divane', 'Yaşar - Topic', '3:52')
  ] });
  assert.deepEqual(results.map(r => [r.url.slice(-11), r.title, r.artist, r.duration, r.topic]), [
    ['OuZWcgB4INw', 'Divane', 'Yaşar', 221000, false],
    ['abcdefghijk', 'Divane', 'Yaşar', 232000, true]
  ]);
});
