import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveMusicUrl } from './resolve.js';

const artist = name => ({ text: name, navigationEndpoint: { browseEndpoint: { browseEndpointContextSupportedConfigs: { browseEndpointContextMusicConfig: { pageType: 'MUSIC_PAGE_TYPE_ARTIST' } } } } });
const ytmSearch = items => ({ contents: { sectionListRenderer: { contents: [{ musicShelfRenderer: { contents: items.map(([videoId, title, name, duration]) => ({
  musicResponsiveListItemRenderer: { playlistItemData: { videoId }, flexColumns: [
    { musicResponsiveListItemFlexColumnRenderer: { text: { runs: [{ text: title }] } } },
    { musicResponsiveListItemFlexColumnRenderer: { text: { runs: [artist(name), { text: ' • ' }, { text: 'Album' }, { text: ' • ' }, { text: duration }] } } }
  ] }
})) } }] } } });
const appleTrack = (id, title, name, ms) => ({ wrapperType: 'track', trackId: id, trackName: title, artistName: name, collectionName: 'Album', trackTimeMillis: ms, trackViewUrl: `https://music.apple.com/tr/album/x/9?i=${id}&uo=4` });
const deezerTrack = (id, title, name, seconds, isrc) => ({ id, title, artist: { name }, album: { title: 'Album' }, duration: seconds, isrc, link: `http://www.deezer.com/track/${id}` });

// Routes each outgoing request to a fixture; unknown hosts fail like a blocked network would.
function mockFetch(routes) {
  const original = globalThis.fetch;
  const calls = [];
  globalThis.fetch = async url => {
    const href = String(url);
    calls.push(href);
    for (const [pattern, body] of routes) {
      if (!href.includes(pattern)) continue;
      const value = typeof body === 'function' ? body(href) : body;
      if (value === null) return new Response('', { status: 404 });
      return new Response(typeof value === 'string' ? value : JSON.stringify(value), { status: 200 });
    }
    return new Response('', { status: 503 });
  };
  return { calls, restore: () => { globalThis.fetch = original; } };
}

const topicDescription = 'Provided to YouTube by DMC\n\nDivane · Yaşar\n\nDivane\n\n℗ 2019 DMC\n\nAuto-generated by YouTube.';

test('a YouTube Music link resolves to exact Apple, Deezer and SoundCloud tracks', async () => {
  const player = { videoDetails: { title: 'Divane', author: 'Yaşar - Topic', lengthSeconds: '252', shortDescription: topicDescription, thumbnail: { thumbnails: [{ url: 'https://i.ytimg.com/vi/a/hq.jpg' }] } } };
  const mock = mockFetch([
    ['www.youtube.com/watch', `<script>var ytInitialPlayerResponse = ${JSON.stringify(player)};</script>`],
    ['itunes.apple.com/search', { results: [appleTrack(1, 'Divane', 'Yaşar', 252500), appleTrack(2, 'Divane (Live)', 'Yaşar', 300000), appleTrack(3, 'Divane', 'Başka Sanatçı', 252000)] }],
    ['api.deezer.com/search', { data: [deezerTrack(11, 'Divane', 'Yaşar', 253, 'TRA111900001')] }],
    ['https://soundcloud.com/', '<script crossorigin src="https://a-v2.sndcdn.com/assets/1-abc.js"></script>'],
    ['a-v2.sndcdn.com/assets/1-abc.js', 'x={client_id:"abcdefghijklmnopqrstuvwxyz123456"}'],
    ['api-v2.soundcloud.com/search/tracks', { collection: [
      { title: 'Divane (cover)', duration: 252000, permalink_url: 'https://soundcloud.com/fan/divane-cover', user: { username: 'fan' } },
      { title: 'Divane', full_duration: 252000, permalink_url: 'https://soundcloud.com/dmc/divane', user: { username: 'DMC' }, publisher_metadata: { artist: 'Yaşar', isrc: 'TRA111900001' } }
    ] }],
    ['musicbrainz.org/ws/2/isrc/TRA111900001', { recordings: [{ title: 'Divane', length: 252000, 'artist-credit': [{ name: 'Yaşar', artist: {} }], relations: [{ url: { resource: 'https://open.spotify.com/track/3V9Cf4pENsRh02WTMJ726n' } }] }] }]
  ]);
  try {
    const result = await resolveMusicUrl('https://youtu.be/abcdefghijk', 'tr');
    const byId = Object.fromEntries(result.platforms.map(p => [p.id, p]));
    assert.equal(result.song.artist, 'Yaşar');
    assert.equal(byId.youtube.url, 'https://music.youtube.com/watch?v=abcdefghijk');
    assert.equal(byId.apple.url, 'https://music.apple.com/tr/album/x/9?i=1');
    assert.equal(byId.deezer.url, 'https://www.deezer.com/track/11');
    assert.equal(byId.soundcloud.url, 'https://soundcloud.com/dmc/divane');
    assert.equal(byId.spotify.url, 'https://open.spotify.com/track/3V9Cf4pENsRh02WTMJ726n');
    assert.ok(result.platforms.every(p => p.exact));
  } finally { mock.restore(); }
});

test('a SoundCloud link with an ISRC finds Deezer by ISRC and YouTube Music by metadata', async () => {
  const hydration = [{ hydratable: 'sound', data: { title: 'Divane', full_duration: 252000, permalink_url: 'https://soundcloud.com/dmc/divane', user: { username: 'DMC' }, publisher_metadata: { artist: 'Yaşar', isrc: 'TRA111900001' } } }];
  const mock = mockFetch([
    ['soundcloud.com/dmc/divane', `<script>window.__sc_hydration = ${JSON.stringify(hydration)};</script>`],
    ['api.deezer.com/track/isrc:TRA111900001', deezerTrack(11, 'Divane', 'Yaşar', 253, 'TRA111900001')],
    ['itunes.apple.com/search', { results: [appleTrack(1, 'Divane', 'Yaşar', 252500)] }],
    ['music.youtube.com/youtubei/v1/search', ytmSearch([['zzzzzzzzzzz', 'Divane', 'Yaşar', '3:10'], ['abcdefghijk', 'Divane', 'Yaşar', '4:12']])]
  ]);
  try {
    const result = await resolveMusicUrl('https://m.soundcloud.com/dmc/divane?si=share', 'tr');
    const byId = Object.fromEntries(result.platforms.map(p => [p.id, p]));
    assert.equal(byId.deezer.url, 'https://www.deezer.com/track/11');
    assert.equal(byId.youtube.url, 'https://music.youtube.com/watch?v=abcdefghijk');
    assert.equal(byId.apple.exact, true);
    assert.equal(byId.spotify.exact, false);
    assert.ok(!mock.calls.some(url => url.includes('api.deezer.com/search')));
  } finally { mock.restore(); }
});

test('a music video matches the unique catalog recording but not an ambiguous one', async () => {
  const player = { videoDetails: { title: 'Tarkan - Şımarık (Official Video)', author: 'TarkanVEVO', lengthSeconds: '265', shortDescription: 'Official video' } };
  const mock = mockFetch([
    ['www.youtube.com/watch', `<script>var ytInitialPlayerResponse = ${JSON.stringify(player)};</script>`],
    ['itunes.apple.com/search', { results: [appleTrack(1, 'Şımarık', 'Tarkan', 237000), appleTrack(2, 'Şımarık', 'Tarkan', 237500)] }],
    ['api.deezer.com/search', { data: [deezerTrack(11, 'Şımarık', 'Tarkan', 237, null), deezerTrack(12, 'Şımarık', 'Tarkan', 330, null)] }]
  ]);
  try {
    const result = await resolveMusicUrl('https://www.youtube.com/watch?v=abcdefghijk');
    const byId = Object.fromEntries(result.platforms.map(p => [p.id, p]));
    assert.equal(result.song.artist, 'Tarkan');
    assert.equal(byId.apple.exact, true);
    assert.equal(byId.deezer.exact, false);
    assert.equal(result.song.duration, 237000);
  } finally { mock.restore(); }
});
