import { fetchJson, fetchText, extractJsonAfter, findAllDeep } from './http.js';
import { cleanChannelName, splitArtistTitle } from './lib.js';

// Consent cookies keep EU visitors from being redirected to consent.youtube.com.
const PAGE_HEADERS = { 'Accept-Language': 'en-US,en;q=0.9', Cookie: 'SOCS=CAI; CONSENT=YES+1' };
const MUSIC_CLIENT = { clientName: 'WEB_REMIX', clientVersion: '1.20250101.01.00', hl: 'en' };
// ytmusicapi's "songs" filter: only official audio tracks, not videos or user uploads.
const SONGS_FILTER = 'EgWKAQIIAWoMEA4QChADEAQQCRAF';

// Auto-generated "Topic" uploads describe the release as:
// "Provided to YouTube by <label>\n\n<title> · <artist> · <artist>\n\n<album>\n\n℗ ..."
export function parseAutoGeneratedDescription(description) {
  const lines = String(description || '').split('\n').map(line => line.trim());
  const start = lines.findIndex(line => line.startsWith('Provided to YouTube by'));
  if (start < 0) return null;
  const rest = lines.slice(start + 1).filter(Boolean);
  const [title, ...artists] = (rest[0] || '').split(' · ').map(part => part.trim());
  if (!title || !artists.length) return null;
  const album = rest[1] && !/^[℗©]/.test(rest[1]) && !/^Released on:/i.test(rest[1]) ? rest[1] : '';
  return { title, artist: artists.join(', '), album };
}

export function youtubeSongFromPlayer(player) {
  const details = player?.videoDetails;
  if (!details?.title) return null;
  const duration = Number(details.lengthSeconds) ? Number(details.lengthSeconds) * 1000 : null;
  const thumbnails = details.thumbnail?.thumbnails || [];
  const artwork = thumbnails.at(-1)?.url || null;
  const release = parseAutoGeneratedDescription(details.shortDescription);
  if (release) return { ...release, duration, artwork, durationReliable: true };
  if (/\s-\sTopic$/i.test(details.author || '')) {
    return { title: details.title, artist: cleanChannelName(details.author), album: '', duration, artwork, durationReliable: true };
  }
  // A music video: "Artist - Title (Official Video)" or a channel named after the artist.
  // Its length often includes intros, so matching must not rely on duration.
  const split = splitArtistTitle(details.title);
  return {
    title: split?.title || details.title,
    artist: split?.artist || cleanChannelName(details.author),
    album: '', duration, artwork, durationReliable: false
  };
}

export async function youtubeMetadata(id) {
  try {
    const html = await fetchText(`https://www.youtube.com/watch?v=${id}&hl=en`, { headers: PAGE_HEADERS });
    const song = youtubeSongFromPlayer(extractJsonAfter(html, 'ytInitialPlayerResponse = '));
    if (song) return song;
  } catch { /* Fall back to oEmbed below. */ }
  const data = await fetchJson(`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}`);
  const topic = /\s-\sTopic$/i.test(data.author_name || '');
  const split = topic ? null : splitArtistTitle(data.title);
  return {
    title: split?.title || data.title,
    artist: split?.artist || cleanChannelName(data.author_name),
    album: '', duration: null, artwork: data.thumbnail_url, durationReliable: false
  };
}

function runsText(column) {
  return (column?.musicResponsiveListItemFlexColumnRenderer?.text?.runs || []).map(run => run.text).join('');
}

export function parseDuration(text) {
  const parts = String(text || '').trim().split(':').map(Number);
  if (parts.length < 2 || parts.length > 3 || parts.some(part => !Number.isInteger(part))) return null;
  return parts.reduce((total, part) => total * 60 + part, 0) * 1000;
}

export function parseMusicSearch(response) {
  return findAllDeep(response, 'musicResponsiveListItemRenderer').map(item => {
    const videoId = item.playlistItemData?.videoId ||
      findAllDeep(item.flexColumns?.[0], 'watchEndpoint')[0]?.videoId;
    if (!/^[\w-]{11}$/.test(videoId || '')) return null;
    const runs = item.flexColumns?.[1]?.musicResponsiveListItemFlexColumnRenderer?.text?.runs || [];
    const artistRuns = runs.filter(run => run.navigationEndpoint?.browseEndpoint?.browseEndpointContextSupportedConfigs
      ?.browseEndpointContextMusicConfig?.pageType === 'MUSIC_PAGE_TYPE_ARTIST');
    const segments = runs.map(run => run.text).join('').split(' • ').map(part => part.trim());
    const artist = artistRuns.length ? artistRuns.map(run => run.text).join(', ') : segments[0] === 'Song' ? segments[1] : segments[0];
    const durationText = [...segments, ...(item.fixedColumns || []).map(runsText)].reverse().find(part => parseDuration(part));
    return {
      title: runsText(item.flexColumns?.[0]),
      artist: artist || '',
      duration: parseDuration(durationText),
      isrc: null,
      url: `https://music.youtube.com/watch?v=${videoId}`
    };
  }).filter(candidate => candidate?.title);
}

export async function searchYoutubeMusic(query, country = 'us') {
  const response = await fetchJson('https://music.youtube.com/youtubei/v1/search?prettyPrint=false', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Origin: 'https://music.youtube.com', Referer: 'https://music.youtube.com/', ...PAGE_HEADERS },
    body: JSON.stringify({ context: { client: { ...MUSIC_CLIENT, gl: country.toUpperCase() } }, query, params: SONGS_FILTER })
  });
  return parseMusicSearch(response);
}
