import { fetchJson, fetchText, extractJsonAfter, findAllDeep } from './http.js';
import { cleanChannelName, splitArtistTitle, artistsOverlap, compactName, youtubeUrl } from './lib.js';

// Consent cookies keep EU visitors from being redirected to consent.youtube.com.
const PAGE_HEADERS = { 'Accept-Language': 'en-US,en;q=0.9', Cookie: 'SOCS=CAI; CONSENT=YES+1' };
const MUSIC_CLIENT = { clientName: 'WEB_REMIX', clientVersion: '1.20250101.01.00', hl: 'en' };
const WEB_CLIENT = { clientName: 'WEB', clientVersion: '2.20250101.00.00', hl: 'en' };
const VIDEO_LABEL = /\s*[([](?:official\s+)?(?:(?:music|lyric)\s+)?(?:video|audio|visuali[sz]er|clip)(?:\s+(?:oficial|officiel|resmi))?[)\]]|\s*[([](?:lyrics?|official|hd|hq|4k|m\/?v|klip|video\s*klip)[)\]]/gi;

const TRAILING_LABEL = /(?:\s+[-|–]\s*|\s+)(?:official\s+)?(?:(?:music\s+)?video(?:\s*klip)?|klip|audio|lyrics?|visuali[sz]er|hd|4k)$/i;

// "Blinding Lights (Official Audio)" → "Blinding Lights", "Gülpembe HD Klip" → "Gülpembe";
// version labels such as "(Live)" stay.
export function cleanVideoTitle(title) {
  let cleaned = String(title || '').replace(VIDEO_LABEL, '').trim();
  for (let previous = ''; previous !== cleaned;) {
    previous = cleaned;
    const next = cleaned.replace(TRAILING_LABEL, '').trim();
    if (next) cleaned = next;
  }
  return cleaned;
}
// ytmusicapi's "songs" filter: only official audio tracks, not videos or user uploads.
const SONGS_FILTER = 'EgWKAQIIAWoMEA4QChADEAQQCRAF';

// Auto-generated "Topic" uploads describe the release as:
// "Provided to YouTube by <label>\n\n<title> · <artist> · <artist>\n\n<album>\n\n℗ ..."
export function parseAutoGeneratedDescription(description) {
  const lines = String(description || '').split('\n').map(line => line.trim());
  const start = lines.findIndex(line => line.startsWith('Provided to YouTube by'));
  if (start < 0) return null;
  const rest = lines.slice(start + 1).filter(Boolean);
  const [title, ...artists] = (rest[0] || '').split(' · ').map(part => part.trim());
  if (!title || !artists.length) return null;
  const album = rest[1] && !/^[℗©]/.test(rest[1]) && !/^Released on:/i.test(rest[1]) ? rest[1] : '';
  return { title, artist: artists.join(', '), album };
}

export function youtubeSongFromPlayer(player) {
  const details = player?.videoDetails;
  if (!details?.title) return null;
  const duration = Number(details.lengthSeconds) ? Number(details.lengthSeconds) * 1000 : null;
  const thumbnails = details.thumbnail?.thumbnails || [];
  const artwork = thumbnails.at(-1)?.url || null;
  const release = parseAutoGeneratedDescription(details.shortDescription);
  if (release) return { ...release, duration, artwork, durationReliable: true };
  if (/\s-\sTopic$/i.test(details.author || '')) {
    return { title: details.title, artist: cleanChannelName(details.author), album: '', duration, artwork, durationReliable: true };
  }
  // A music video: "Artist - Title (Official Video)" or a channel named after the artist.
  // Its length often includes intros, so matching must not rely on duration.
  const split = splitArtistTitle(details.title);
  return {
    title: cleanVideoTitle(split?.title || details.title),
    artist: split?.artist || cleanChannelName(details.author),
    album: '', duration, artwork, durationReliable: false
  };
}

// The innertube player endpoint answers where the watch page shows a consent or bot-check page.
async function youtubePlayer(id) {
  return fetchJson('https://www.youtube.com/youtubei/v1/player?prettyPrint=false', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...PAGE_HEADERS },
    body: JSON.stringify({ context: { client: WEB_CLIENT }, videoId: id })
  });
}

export async function youtubeMetadata(id) {
  try {
    const song = youtubeSongFromPlayer(await youtubePlayer(id));
    if (song) return song;
  } catch { /* Try the watch page next. */ }
  try {
    const html = await fetchText(`https://www.youtube.com/watch?v=${id}&hl=en`, { headers: PAGE_HEADERS });
    const song = youtubeSongFromPlayer(extractJsonAfter(html, 'ytInitialPlayerResponse = '));
    if (song) return song;
  } catch { /* Fall back to oEmbed below. */ }
  const data = await fetchJson(`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}`);
  const topic = /\s-\sTopic$/i.test(data.author_name || '');
  const split = topic ? null : splitArtistTitle(data.title);
  return {
    title: cleanVideoTitle(split?.title || data.title),
    artist: split?.artist || cleanChannelName(data.author_name),
    album: '', duration: null, artwork: data.thumbnail_url, durationReliable: false
  };
}

function runsText(column) {
  return (column?.musicResponsiveListItemFlexColumnRenderer?.text?.runs || []).map(run => run.text).join('');
}

export function parseDuration(text) {
  const parts = String(text || '').trim().split(':').map(Number);
  if (parts.length < 2 || parts.length > 3 || parts.some(part => !Number.isInteger(part))) return null;
  return parts.reduce((total, part) => total * 60 + part, 0) * 1000;
}

export function parseMusicSearch(response) {
  return findAllDeep(response, 'musicResponsiveListItemRenderer').map(item => {
    const videoId = item.playlistItemData?.videoId ||
      findAllDeep(item.flexColumns?.[0], 'watchEndpoint')[0]?.videoId;
    if (!/^[\w-]{11}$/.test(videoId || '')) return null;
    const runs = item.flexColumns?.[1]?.musicResponsiveListItemFlexColumnRenderer?.text?.runs || [];
    const artistRuns = runs.filter(run => run.navigationEndpoint?.browseEndpoint?.browseEndpointContextSupportedConfigs
      ?.browseEndpointContextMusicConfig?.pageType === 'MUSIC_PAGE_TYPE_ARTIST');
    const segments = runs.map(run => run.text).join('').split(' • ').map(part => part.trim());
    const artist = artistRuns.length ? artistRuns.map(run => run.text).join(', ') : segments[0] === 'Song' ? segments[1] : segments[0];
    const durationText = [...segments, ...(item.fixedColumns || []).map(runsText)].reverse().find(part => parseDuration(part));
    return {
      title: runsText(item.flexColumns?.[0]),
      artist: artist || '',
      duration: parseDuration(durationText),
      isrc: null,
      videoId,
      url: youtubeUrl('youtubeMusic', videoId)
    };
  }).filter(candidate => candidate?.title);
}

export async function searchYoutubeMusic(query, country = 'us') {
  const response = await fetchJson('https://music.youtube.com/youtubei/v1/search?prettyPrint=false', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Origin: 'https://music.youtube.com', Referer: 'https://music.youtube.com/', ...PAGE_HEADERS },
    body: JSON.stringify({ context: { client: { ...MUSIC_CLIENT, gl: country.toUpperCase() } }, query, params: SONGS_FILTER })
  });
  return parseMusicSearch(response);
}

// Regular YouTube search, limited to uploads that can be trusted as official:
// auto-generated "Topic" channels (the YouTube Music song itself), verified artist channels,
// and verified label channels ("netd müzik").
export function parseVideoSearch(response) {
  return findAllDeep(response, 'videoRenderer').map(video => {
    const channel = (video.ownerText?.runs || []).map(run => run.text).join('');
    const badges = (video.ownerBadges || []).map(badge => badge.metadataBadgeRenderer?.style);
    const topic = /\s-\sTopic$/i.test(channel);
    const artistChannel = badges.includes('BADGE_STYLE_TYPE_VERIFIED_ARTIST');
    if (!/^[\w-]{11}$/.test(video.videoId || '') || !(topic || artistChannel || badges.includes('BADGE_STYLE_TYPE_VERIFIED'))) return null;
    const channelName = cleanChannelName(channel);
    // Bilingual titles add " | <other script>"; only the first part names the song.
    const rawTitle = (video.title?.runs || []).map(run => run.text).join('').split(/\s+\|{1,2}\s+/)[0];
    const split = splitArtistTitle(rawTitle);
    const titleArtist = compactName(String(split?.artist || '').split(',')[0]);
    // An artist channel counts as the artist's own only if its name agrees with the artist in the title;
    // otherwise it is another artist's upload (possibly a cover) and is held to the label rules.
    const ownChannel = artistChannel && (!split || artistsOverlap(channelName, split.artist) || (titleArtist.length >= 3 && compactName(channelName).includes(titleArtist)));
    const label = !topic && !ownChannel && (artistChannel || badges.includes('BADGE_STYLE_TYPE_VERIFIED'));
    // A Topic upload's title is the song. Artist and label channels title uploads "Artist - Title";
    // an artist channel's name may differ from the artist ("barismancotv"), so the title names the artist.
    let artist = channelName;
    let title = rawTitle;
    if (split && (!topic || artistsOverlap(channelName, split.artist))) ({ artist, title } = topic ? { artist, title: split.title } : split);
    title = cleanVideoTitle(title);
    // Label channels also upload live and TV performances: only plain "Artist - Title" uploads count.
    if (label && (!split || /[([]/.test(title))) return null;
    return {
      title,
      artist,
      duration: parseDuration(video.lengthText?.simpleText),
      isrc: null,
      official: topic ? 'topic' : ownChannel ? 'artist' : 'label',
      topic,
      videoId: video.videoId,
      url: youtubeUrl('youtube', video.videoId)
    };
  }).filter(Boolean);
}

export async function searchYoutubeVideos(query, country = 'us') {
  const response = await fetchJson('https://www.youtube.com/youtubei/v1/search?prettyPrint=false', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...PAGE_HEADERS },
    body: JSON.stringify({ context: { client: { ...WEB_CLIENT, gl: country.toUpperCase() } }, query })
  });
  return parseVideoSearch(response);
}

// YouTube Music's "next" response for a song names its album (a MPREb_ browse id), which is the album's page.
export function albumOfSong(response) {
  const run = findAllDeep(response, 'runs').flat().find(item => item?.navigationEndpoint?.browseEndpoint?.browseId?.startsWith('MPREb_'));
  return run ? { title: run.text, url: `https://music.youtube.com/browse/${run.navigationEndpoint.browseEndpoint.browseId}` } : null;
}

export async function youtubeMusicAlbumOfVideo(videoId) {
  const response = await fetchJson('https://music.youtube.com/youtubei/v1/next?prettyPrint=false', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Origin: 'https://music.youtube.com', Referer: 'https://music.youtube.com/', ...PAGE_HEADERS },
    body: JSON.stringify({ context: { client: MUSIC_CLIENT }, videoId, isAudioOnly: true })
  });
  return albumOfSong(response);
}

// An OLAK5uy_ album playlist: oEmbed gives "Album - <title>" and its first video, whose Topic upload names the artist.
export async function youtubeAlbumMetadata(list) {
  const data = await fetchJson(`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(`https://www.youtube.com/playlist?list=${list}`)}`);
  const title = String(data.title || '').replace(/^Album\s*[-–]\s*/i, '');
  const firstVideo = String(data.thumbnail_url || '').match(/\/vi\/([\w-]{11})\//)?.[1];
  const first = firstVideo ? await youtubeMetadata(firstVideo).catch(() => null) : null;
  return { title, artist: first?.artist || '', trackCount: null, year: null, upc: null, artwork: data.thumbnail_url || null, tracks: first ? [first] : [] };
}
