// Copies the website's public/ files into www/ for the app and points the app at the public server.
// TUNEBRIDGE_URL sets that server (default: the production site).
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.join(here, '..', 'public');
const target = path.join(here, 'www');
const server = (process.env.TUNEBRIDGE_URL || 'https://tunebridge-nine.vercel.app').replace(/\/$/, '');

await fs.rm(target, { recursive: true, force: true });
await fs.cp(source, target, { recursive: true });
// The app is not an installable web app: drop the service worker and the install manifest's share target.
await fs.writeFile(path.join(target, 'sw.js'), '// Not used inside the app.\n');
await fs.writeFile(path.join(target, 'config.js'),
  `// Generated by mobile/build-www.mjs\nwindow.TUNEBRIDGE = { apiBase: ${JSON.stringify(server)}, publicBase: ${JSON.stringify(server)}, app: true };\n`);
console.log(`www/ ready, server ${server}`);
